project:
    type: website

website:
  title: "Christopher Lee Praley"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
        
output-dir: docs

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true