project:
    type: website
    output-dir: docs

website:
  title: "Christopher Lee Praley"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects and Work"
        href: projects.qmd
      - text: "Resume"
        href: resume.qmd

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true